# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a-YYQcWLUoN2SxTpbS-sUahx7K3su1DG
"""

n=int(input("enter your number"))
sum=0
counter=1
while counter<=n:
  sum=sum+counter
  counter=counter+1
print(sum)

n=int(input("enter a number"))
fact=1
while n>0:
  fact= fact*n
  n=n-1
print(fact)

n=int(input("enter a number"))
fact=1
while n>0:
  fact= fact*n
  n=n-1
print(fact)

n=int(input("enter the number"))
a,b=0,1
for i in range(n):
  print(a)
  c=a+b
  a=b
  b=c

word= str(input("enter your string"))
reverse=""
length=len(word)
while length>0:
  reverse=reverse+word[length-1]
  length=length-1
print(reverse)

counter=1
n=int(input("enter the number"))
while counter<=10:
  result=counter*n
  counter=counter+1
  print(result)

n=int(input("enter the number"))
for i in range (1,11):
  result= n*i
  print(result)

